authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('rights_checking/', authapp.rights_checking, name='rights_checking'),
]

pioner_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    path('students/', include('studentsapp.urls', namespace='students')),
    path('eduprograms/', include('eduprogramsapp.urls', namespace='eduprograms')),
    path('timetables/', include('timetableapp.urls', namespace='timetables')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

pioner_prj/views.py
from django.shortcuts import render


def index(request):
    context = {
        'title': 'главная',
    }

    return render(request, 'pioner_prj/index.html', context=context)


def contacts(request):
    context = {
        'title': 'контакты',
    }

    return render(request, 'pioner_prj/contacts.html', context=context)

pioner_prj/templates/pioner_prj/includes/inc_footer.html
<div class="container">
    <footer class="">
    </footer>
</div>

pioner_prj/templates/pioner_prj/includes/inc_header.html
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <ul id="menu" class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li hidden=true><a id="index" href="{% url 'index' %}" class="nav-link px-2 link-dark" data-rights="">Главная</a></li>
            <li hidden=true><a id="students" href="{% url 'students:index' %}" class="nav-link px-2 link-dark" data-rights="">Обучающиеся</a></li>
            <li hidden=true><a id="programs" href="{% url 'eduprograms:index' %}" class="nav-link px-2 link-dark" data-rights="is_methodist">Образовательные программы</a></li>
            <li hidden=true><a id="timetables" href="{% url 'timetables:index' %}" class="nav-link px-2 link-dark" data-rights="is_timetable_manager">Расписание</a></li>
            <li hidden=true><a id="contacts" href="{% url 'contacts' %}" class="nav-link px-2 link-dark" data-rights="">Контакты</a></li>
        </ul>
        <div class="col-md-3 text-end">
            {% if user.is_authenticated %}
                <button type="button" class="btn btn-primary">
                    <a href="{% url 'auth:edit' %}" class="nav-link px-2">
                        {{ user.first_name|default:'Пользователь' }} {{ user.last_name|default:'' }}
                    </a>
                </button>
                <button type="button" class="btn btn-outline-primary me-2">
                    <a href="{% url 'auth:logout' %}" class="nav-link px-2">Выйти</a>
                </button>
            {% else %}
                <button type="button" class="btn btn-outline-primary me-2">
                    <a href="{% url 'auth:login' %}" class="nav-link px-2">Войти</a>
                </button>
                <button type="button" class="btn btn-primary">
                    <a href="{% url 'auth:register' %}" class="nav-link px-2">Зарегистрироваться</a>
                </button>
            {% endif %}
        </div>
    </header>
</div>