authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('rights_checking/', authapp.rights_checking, name='rights_checking'),
]

eduprogramsapp/urls.py
from django.urls import path
from .views import eduprograms, eduprogram_edit, eduprogram_create

app_name = 'eduprogramsapp'

urlpatterns = [
    path('', eduprograms, name='index'),
    path('eduprogram/create/', eduprogram_create, name='eduprogram_create'),
    path('eduprogram/edit/<int:pk>/', eduprogram_edit, name='eduprogram_edit'),
]

pioner_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    path('students/', include('studentsapp.urls', namespace='students')),
    path('eduprograms/', include('eduprogramsapp.urls', namespace='eduprograms')),
    path('timetables/', include('timetableapp.urls', namespace='timetables')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

eduprogramsapp/models.py
from django.db import models


class TypeProgram(models.Model):
    name = models.CharField(verbose_name='Тип', max_length=30, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)

    def __str__(self):
        _ = self.name.split()
        return f'ДО{self.name[0].upper()}П' if len(_) == 1 else f'ДОП{_[0][0].upper()}{_[0][1].upper()}'


class OrientationProgram(models.Model):
    name = models.CharField(verbose_name='Направленность', max_length=30, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)

    def __str__(self):
        return f'{self.name}'


class EduProgram(models.Model):
    class StatusChoice(models.TextChoices):
        ACTIVE_PROGRAM = 'A', 'Реализуется'
        NOT_ACTIVE_PROGRAM = 'NA', 'Не реализуется'
        DELETED_PROGRAM = 'D', 'Удалена'

    type = models.ForeignKey(
        TypeProgram,
        verbose_name='Тип программы',
        on_delete=models.SET_DEFAULT,
        default=None
    )

    orientation = models.ForeignKey(
        OrientationProgram,
        verbose_name='Направленность программы',
        on_delete=models.SET_DEFAULT,
        default=None
    )

    is_adapted = models.BooleanField(verbose_name='Адаптированность', default=False)
    duration = models.IntegerField(verbose_name='Продолжительность, ч', default=8)
    name = models.CharField(verbose_name='Наименование', max_length=250, blank=False, unique=True)
    description = models.TextField(verbose_name='Описание', blank=False)
    program_status = models.CharField(
        verbose_name='Статус программы',
        max_length=20,
        choices=StatusChoice.choices,
        blank=False,
        default=StatusChoice.NOT_ACTIVE_PROGRAM,
    )

    def __str__(self):
        return f'{self.type} "{self.name}"'


class WorkProgram(models.Model):
    edu_program = models.ForeignKey(
        EduProgram,
        verbose_name='Основная программа',
        on_delete=models.CASCADE,
        blank=False
    )
    duration = models.IntegerField(verbose_name='Продолжительность, ч')
    name = models.CharField(verbose_name='Наименование', max_length=250, blank=False)
    description = models.TextField(verbose_name='Описание', blank=False)

eduprogramsapp/forms.py
from django import forms

from .models import EduProgram


class EduProgramForm(forms.ModelForm):
    class Meta:
        model = EduProgram
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EduProgramForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name[:2] == 'is':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

eduprogramsapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import EduProgram
from .forms import EduProgramForm


@login_required
def eduprograms(request):
    eduprograms = EduProgram.objects.all().order_by('id')

    context = {
        'title': 'Образовательные программы',
        'eduprograms': eduprograms,
    }

    return render(request, 'eduprogramsapp/eduprograms.html', context=context)


@login_required
def eduprogram_create(request):
    title = 'Создание ДОП'

    if request.method == 'POST':
        eduprogram_form = EduProgramForm(request.POST)
        if eduprogram_form.is_valid():
            new_eduprogram = eduprogram_form.save(commit=False)
            eduprogram_form.save()
            return HttpResponseRedirect(reverse('eduprogramsapp:eduprogram_edit', args=[new_eduprogram.pk]))
    else:
        eduprogram_form = EduProgramForm()

    context = {
        'title': title,
        'eduprogram_form': eduprogram_form,
    }

    return render(request, 'eduprogramsapp/eduprogram_create.html', context=context)


@login_required
def eduprogram_edit(request, pk):
    edit_eduprogram = get_object_or_404(EduProgram, pk=pk)

    if request.method == 'POST':
        eduprogram_form = EduProgramForm(request.POST, instance=edit_eduprogram)
        if eduprogram_form.is_valid():
            eduprogram_form.save()
            return HttpResponseRedirect(reverse('eduprogramsapp:eduprogram_edit', args=[edit_eduprogram.pk]))
    else:
        eduprogram_form = EduProgramForm(instance=edit_eduprogram)

    context = {
        'title': edit_eduprogram.name,
        'eduprogram_form': eduprogram_form,
    }

    return render(request, 'eduprogramsapp/eduprogram_edit.html', context=context)

eduprogramsapp/templates/eduprogramsapp/eduprogram_create.html
{% extends 'pioner_prj/base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <h4 class="mb-3">Новая дополнительная общеобразовательная программа</h4>
  <div class="row">
    <div class="col">
      <form class="needs-validation" novalidate="" method="post">
        {% csrf_token %}
        {{ eduprogram_form.as_p }}
        <button class="w-100 btn btn-lg btn-primary" type="submit">
          Создать программу
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

eduprogramsapp/templates/eduprogramsapp/eduprogram_edit.html
{% extends 'pioner_prj/base.html' %}
{% load static %}

{% block js %}
  {{ block.super }}
  <script src="{% static 'js/left_menu.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
  <h4 class="mb-3">{{ eduprogram.name }}</h4>
  <div class="row">
    <div class="col-md-auto">
      <ul class="list-group align-middle">
        <li class="list-group-item"><p>Основная программа</p></li>
        <li class="list-group-item"><p>Рабочие программы</p></li>
        <li class="list-group-item"><p>КТП</p></li>
      </ul>
    </div>
    <div class="col">
      <form class="needs-validation" novalidate="" method="post">
        {% csrf_token %}
        {{ eduprogram_form.as_p }}
        <button class="w-100 btn btn-lg btn-primary" type="submit">
                Сохранить изменения
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

eduprogramsapp/templates/eduprogramsapp/eduprograms.html
{% extends 'pioner_prj/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <button type="button" class="btn btn-primary">
            <a href="{% url 'eduprograms:eduprogram_create' %}" class="nav-link px-2">Создать новую ДОП</a>
        </button>
        <div class="bd-example-snippet bd-code-snippet">
            <div class="bd-example">
                <table class="table table-stripped">
                    <thread>
                        <tr>
                            <th scope="col">Id</th>
                            <th scope="col">Тип</th>
                            <th scope="col">Направленность</th>
                            <th scope="col">Наименование</th>
                            <th scope="col">Продолжительность</th>
                            <th scope="col">Адапт.</th>
                            <th scope="col"></th>
                        </tr>
                    </thread>
                    <tbody>
                    {% for eduprogram in eduprograms %}
                        <tr>
                            <th scope="row">{{ eduprogram.id }}</th>
                            <td>{{ eduprogram.type }}</td>
                            <td>{{ eduprogram.orientation }}</td>
                            <td>{{ eduprogram.name }}</td>
                            <td>{{ eduprogram.duration }}</td>
                            <td>{% if eduprogram.is_adapted %} &#10003; {% endif %}</td>
                            <td>
                                <button type="button" class="btn btn-outline-primary me-2">
                                    <a href="{% url 'eduprograms:eduprogram_edit' eduprogram.pk %}" class="nav-link px-2">Редактировать</a>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}