authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('rights_checking/', authapp.rights_checking, name='rights_checking'),
]

pioner_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    path('students/', include('studentsapp.urls', namespace='students')),
    path('eduprograms/', include('eduprogramsapp.urls', namespace='eduprograms')),
    path('timetables/', include('timetableapp.urls', namespace='timetables')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

studentsapp/urls.py
from django.urls import path
from .views import students, student_create, student_edit

app_name = 'studentsapp'

urlpatterns = [
    path('', students, name='index'),
    path('student/create/', student_create, name='student_create'),
    path('student/edit/<int:pk>/', student_edit, name='student_edit'),
]

studentsapp/models.py
from django.db import models
from eduprogramsapp.models import EduProgram


class SocialStatus(models.Model):
    name = models.CharField(verbose_name='Наименование статуса', max_length=30, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)

    def __str__(self):
        return f'{self.name}'


class HealthLimitations(models.Model):
    name = models.CharField(verbose_name='Наименование ОВЗ', max_length=50, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)

    def __str__(self):
        return f'{self.name}'


class Student(models.Model):
    last_name = models.CharField(verbose_name='Фамилия', max_length=20)
    first_name = models.CharField(verbose_name='Имя', max_length=20)
    patronymic = models.CharField(verbose_name='Отчество', max_length=20)
    birth_date = models.DateField(verbose_name='Дата рождения')
    social_status = models.ForeignKey(SocialStatus, on_delete=models.SET_DEFAULT, default=None)
    health_limitations = models.ForeignKey(HealthLimitations, on_delete=models.SET_DEFAULT, default=None)
    disability = models.BooleanField(verbose_name='Инвалидность', default=False)
    edu_program = models.ManyToManyField(EduProgram)  # ДОП

studentsapp/forms.py
from django import forms

from .models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

studentsapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Student
from .forms import StudentForm


@login_required
def students(request):
    students = Student.objects.all().order_by('first_name')

    context = {
        'title': 'обучающиеся',
        'students': students,
    }

    return render(request, 'studentsapp/students.html', context=context)


@login_required
def student_create(request):
    title = 'Создание карточки обучающегося'

    if request.method == 'POST':
        student_form = StudentForm(request.POST)
        if student_form.is_valid():
            student_form.save()
            return HttpResponseRedirect('/students/')
    else:
        student_form = StudentForm()

    context = {
        'title': title,
        'student_form': student_form,
    }

    return render(request, 'studentsapp/student_create.html', context=context)


@login_required
def student_edit(request, pk):
    edit_student = get_object_or_404(Student, pk=pk)

    if request.method == 'POST':
        student_form = StudentForm(request.POST, instance=edit_student)
        if student_form.is_valid():
            student_form.save()
            return HttpResponseRedirect(reverse('studentsapp:student_edit', args=[edit_student.pk]))
    else:
        student_form = StudentForm(instance=edit_student)

    context = {
        'title': f'{edit_student.first_name} {edit_student.last_name}',
        # 'student': edit_student,
        'student_form': student_form,
    }

    return render(request, 'studentsapp/student_edit.html', context=context)

studentsapp/templates/studentsapp/student_create.html
{% extends 'pioner_prj/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h4 class="mb-3">Новый обучающийся</h4>
    <form class="needs-validation" novalidate="" method="post">
        {% csrf_token %}
        {{ student_form }}
        <button class="w-100 btn btn-lg btn-primary" type="submit">
                Создать новую карточку обучающегося
        </button>
    </form>
</div>
{% endblock %}

studentsapp/templates/studentsapp/student_edit.html
{% extends 'pioner_prj/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h4 class="mb-3">{{ student.first_name }} {{ student.last_name }}</h4>
    <form class="needs-validation" novalidate="" method="post">
        {% csrf_token %}
        {{ student_form }}
        <button class="w-100 btn btn-lg btn-primary" type="submit">
                Сохранить изменения
        </button>
    </form>
</div>
{% endblock %}

studentsapp/templates/studentsapp/students.html
{% extends 'pioner_prj/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <button type="button" class="btn btn-primary">
            <a href="{% url 'students:student_create' %}" class="nav-link px-2">Добавить обучающегося</a>
        </button>
        <div class="bd-example-snippet bd-code-snippet">
            <div class="bd-example">
                <table class="table table-stripped">
                    <thread>
                        <tr>
                            <th scope="col">Id</th>
                            <th scope="col">Имя</th>
                            <th scope="col">Фамилия</th>
                            <th scope="col">Отчество</th>
                            <th scope="col">Дата рождения</th>
                            <th scope="col"></th>
                        </tr>
                    </thread>
                    <tbody>
                    {% for student in students %}
                        <tr>
                            <th scope="row">{{ student.id }}</th>
                            <td>{{ student.first_name }}</td>
                            <td>{{ student.last_name }}</td>
                            <td>{{ student.patronymic }}</td>
                            <td>{{ student.birth_date }}</td>
                            <td>
                                <button type="button" class="btn btn-outline-primary me-2">
                                    <a href="{% url 'students:student_edit' student.pk %}" class="nav-link px-2">Редактировать</a>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}